admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

impact:
    resource: "@ImpactBundle/Resources/config/routing.yml"
    prefix:   /

admin_bundle:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"