impact_homepage:
    path:     /
    defaults: { _controller: ImpactBundle:Default:index }

impact_forum:
    path:     /forum
    defaults: { _controller: ImpactBundle:Forum:index }

impact_forum_admin:
    path:     /forum/admin
    defaults: { _controller: ImpactBundle:Admin:index }

impact_about:
    path:     /hermandad
    defaults: { _controller: ImpactBundle:Default:about }

discutea_forum_category_routing:
    resource: "@ImpactBundle/Controller/CategoryController.php"
    prefix:   /forum
    type:     annotation

discutea_forum_forum_routing:
    resource: "@ImpactBundle/Controller/ForumController.php"
    prefix:   /forum
    type:     annotation

discutea_forum_topic_routing:
    resource: "@ImpactBundle/Controller/TopicController.php"
    prefix:   /forum
    type:     annotation

discutea_forum__post_routing:
    resource: "@ImpactBundle/Controller/PostController.php"
    prefix:   /forum
    type:     annotation

discutea_forum_label_routing:
    resource: "@ImpactBundle/Controller/LabelController.php"
    prefix:   /forum
    type:     annotation

discutea_forum_admin_routing:
    resource: "@ImpactBundle/Controller/AdminController.php"
    prefix:   /forum
    type:     annotation

