user_bundle_homepage:
    path:     /admin/user
    defaults: { _controller: UserBundle:Default:index }

user_bundle_editprofile:
    path:     /admin/editprofile/
    defaults: { _controller: FOSUserBundle:Profile:administrarUser }

user_bundle_edit:
    path:     /admin/edit/{id}
    defaults: { _controller: UserBundle:Default:edit }

#user_bundle_delete:
#    path:     /delete/{id}
#   defaults: { _controller: HotelBundleUsuariBundle:Default:delete }lokurax
