user_bundle_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

##hotel_bundle_usuari_editprofile:
#    path:     /editprofile/
#    defaults: { _controller: FOSUserBundle:Profile:administrarUser }

#hotel_bundle_usuari_edit:
#    path:     /edit/{id}
#    defaults: { _controller: HotelBundleUsuariBundle:Default:edit }

#hotel_bundle_usuari_delete:
#    path:     /delete/{id}
#    defaults: { _controller: HotelBundleUsuariBundle:Default:delete }